class_name ContentScan
extends RefCounted
## Finds content files under a directory. One walk, used by everything that discovers data.
##
## It exists because the project had FOUR of these, and they disagreed. Registry's walk
## recursed; the art generator's, the art fixtures' and Sprite Lab's did not. So a character
## spec in a subdirectory was registered by Registry, never generated by gen_sprites, and the
## art-drift gate reported green on art it had never looked at - a gate evaluating less than
## it claims, which is the failure this repo keeps finding. A discovery rule written down
## four times is four rules that drift apart.
##
## Results are SORTED, and that is load-bearing rather than tidy: DirAccess returns entries
## in filesystem order, so an unsorted walk lets the order of the generated contact sheet
## depend on which machine ran the generator.
##
## Exported projects rename `x.tres` to `x.tres.remap`; the suffix is stripped before the
## extension is tested, so the same walk works from a .pck.

const RESOURCE_EXTS: Array[String] = ["tres", "res"]

## Directories that are never content: someone else's source, and build caches.
const SKIP_DIRS: Array[String] = ["addons", ".godot", ".git", ".import"]


## Every file under `root` whose extension is in `extensions`, sorted, as res:// paths.
## A missing directory is empty, not an error - callers scan optional content roots.
static func files(root: String, extensions: Array[String]) -> Array[String]:
	return in_order(once_each(_walk(root, extensions)))


## One entry per source file, keeping the first.
##
## Necessary the moment `source_name` started resolving a sidecar to the file it stands for:
## HERE both exist - `hit.wav` and `hit.wav.import` sit side by side - so the same sound
## resolved twice, while in an exported build only the sidecar is packed and it resolves once.
## A walk that double-counts in one environment and not the other is worse than either, and it
## surfaced as a work list of thirty-two cues where sixteen ship.
##
## A function over a list, for the same reason in_order is: what a directory contains cannot be
## forced from a test, and what a list contains can.
static func once_each(paths: Array[String]) -> Array[String]:
	var out: Array[String] = []
	var seen: Dictionary = {}
	for path in paths:
		if seen.has(path):
			continue
		seen[path] = true
		out.append(path)
	return out


## The ordering contract, as a function over a list rather than over a directory.
##
## It is separate from the walk because DirAccess order cannot be forced from a test: it is
## already alphabetical on one filesystem and is not on another, so a mutant aimed at a sort
## inside the walk was killed on macOS and SURVIVED on the Ubuntu runner - the assertion was
## decoration on exactly the machine that gates the merge. Given the list, ordering is
## provable anywhere.
static func in_order(paths: Array[String]) -> Array[String]:
	var out := paths.duplicate()
	out.sort()
	return out


## Convenience for the common case of a single extension.
static func files_of(root: String, extension: String) -> Array[String]:
	var one: Array[String] = [extension]
	return files(root, one)


## Every resource under `root` that loads, in the same order as files(). One that fails to
## load is skipped rather than fatal: the loader has already pushed its own error, and a
## caller that needs to know about it should validate the count it expected.
static func resources(root: String, extensions: Array[String] = RESOURCE_EXTS) -> Array[Resource]:
	var out: Array[Resource] = []
	for path in files(root, extensions):
		var res: Resource = load(path)
		if res != null:
			out.append(res)
	return out


## The name of the SOURCE file a packed entry stands for.
##
## An exported build does not contain the files you put in it. A `.tres` is packed beside a
## `.remap`, and an IMPORTED asset - every png, wav, ogg - is packed as its `.import` sidecar
## plus the engine's cached copy, with the original left out entirely. So a walk looking for
## "ogg" finds nothing in a shipped build while working perfectly in the editor.
##
## That is not hypothetical: it is why AudioBus could scan `data/audio` happily here and come
## up empty on the deployed page. Kept as a pure function over a NAME so it can be tested
## without putting an orphan `.import` on disk, which would confuse the importer and break the
## exact-array assertion the walk's own suite makes.
static func source_name(file_name: String) -> String:
	return file_name.trim_suffix(".remap").trim_suffix(".import")


static func _walk(root: String, extensions: Array[String]) -> Array[String]:
	var out: Array[String] = []
	var dir := DirAccess.open(root)
	if dir == null:
		return out
	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		var full := root.path_join(name)
		if dir.current_is_dir():
			if not name.begins_with(".") and not SKIP_DIRS.has(name):
				out.append_array(_walk(full, extensions))
		else:
			var check := source_name(name)
			if extensions.has(check.get_extension()):
				out.append(root.path_join(check))
		name = dir.get_next()
	dir.list_dir_end()
	return out
