class_name ContentScan
extends RefCounted
## Finds content files under a directory. One walk, used by everything that discovers data.
##
## It exists because the project had FOUR of these, and they disagreed. Registry's walk
## recursed; the art generator's, the art fixtures' and Sprite Lab's did not. So a character
## spec in a subdirectory was registered by Registry, never generated by gen_sprites, and the
## art-drift gate reported green on art it had never looked at - a gate evaluating less than
## it claims, which is the failure this repo keeps finding. A discovery rule written down
## four times is four rules that drift apart.
##
## Results are SORTED, and that is load-bearing rather than tidy: DirAccess returns entries
## in filesystem order, so an unsorted walk lets the order of the generated contact sheet
## depend on which machine ran the generator.
##
## Exported projects rename `x.tres` to `x.tres.remap`; the suffix is stripped before the
## extension is tested, so the same walk works from a .pck.

const RESOURCE_EXTS: Array[String] = ["tres", "res"]

## Directories that are never content: someone else's source, and build caches.
const SKIP_DIRS: Array[String] = ["addons", ".godot", ".git", ".import"]


## Every file under `root` whose extension is in `extensions`, sorted, as res:// paths.
## A missing directory is empty, not an error - callers scan optional content roots.
static func files(root: String, extensions: Array[String]) -> Array[String]:
	var out := _walk(root, extensions)
	out.sort()
	return out


## Convenience for the common case of a single extension.
static func files_of(root: String, extension: String) -> Array[String]:
	var one: Array[String] = [extension]
	return files(root, one)


## Every resource under `root` that loads, in the same order as files(). One that fails to
## load is skipped rather than fatal: the loader has already pushed its own error, and a
## caller that needs to know about it should validate the count it expected.
static func resources(root: String, extensions: Array[String] = RESOURCE_EXTS) -> Array[Resource]:
	var out: Array[Resource] = []
	for path in files(root, extensions):
		var res: Resource = load(path)
		if res != null:
			out.append(res)
	return out


static func _walk(root: String, extensions: Array[String]) -> Array[String]:
	var out: Array[String] = []
	var dir := DirAccess.open(root)
	if dir == null:
		return out
	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		var full := root.path_join(name)
		if dir.current_is_dir():
			if not name.begins_with(".") and not SKIP_DIRS.has(name):
				out.append_array(_walk(full, extensions))
		else:
			var check := name.trim_suffix(".remap")
			if extensions.has(check.get_extension()):
				out.append(root.path_join(check))
		name = dir.get_next()
	dir.list_dir_end()
	return out
