extends GdUnitTestSuite
## What is COMMITTED, checked against what the template says should exist.
##
## The drift gate already proves the samples match the generator. This proves the things a
## drift gate structurally cannot see, because they are about the SET of files and about what
## happens to them on the way into a shipped build:
##
##   - a cue removed from the vocabulary leaves its WAV behind forever, generated by nothing
##   - a WAV committed without its .import sidecar is not packed into an export at all
##   - the importer is free to transcode, so the stream the game plays may not be the one that
##     was checked - and every surface anyone looks at would still say the file is fine
##
## The last one is the same shape as this project's colour-in-floats lesson, one layer up: two
## sides agreeing on the formula and disagreeing on the answer, because a store sat between.

const GENERATED := "res://assets/generated"
const SFX_SUBDIR := "sfx"


func _sfx_dirs() -> Array[String]:
	var out: Array[String] = []
	for res in ContentScan.resources("res://data/sounds", ["tres"] as Array[String]):
		var style := res as SoundStyle
		if style != null:
			out.append("%s/%s/%s" % [GENERATED, style.id, SFX_SUBDIR])
	return out


func test_there_is_generated_audio_to_check() -> void:
	var dirs := _sfx_dirs()
	assert_int(dirs.size()).override_failure_message(
		"no sound styles ship, so every assertion in this suite is vacuous").is_greater(0)
	for dir in dirs:
		assert_int(ContentScan.files(dir, ["wav"]).size()).override_failure_message(
			"%s holds no cues" % dir).is_greater(0)


func test_each_style_ships_exactly_the_cues_the_template_names() -> void:
	for dir in _sfx_dirs():
		var on_disk: Array[String] = []
		for path in ContentScan.files(dir, ["wav"]):
			on_disk.append(path.get_file().get_basename())
		on_disk.sort()
		var wanted: Array[String] = []
		for id in Sfx.ids():
			wanted.append(String(id))
		wanted.sort()
		assert_array(on_disk).override_failure_message(
			"%s ships %s; the template asks for %s" % [dir, on_disk, wanted]).is_equal(wanted)


func test_every_generated_asset_has_its_import_sidecar_committed() -> void:
	# A generated file with no .import is not packed as a resource on a fresh clone, so it
	# works here and is missing in the export - which is the one place nobody is watching.
	# Checked for art as well as audio: the hazard is the pipeline's, not this milestone's.
	var checked := 0
	for extension in ["wav", "png"]:
		for path in ContentScan.files(GENERATED, [extension] as Array[String]):
			assert_bool(FileAccess.file_exists(path + ".import")).override_failure_message(
				"%s has no committed .import beside it" % path).is_true()
			checked += 1
	assert_int(checked).is_greater(0)


func test_the_stream_the_game_loads_is_the_one_that_was_committed() -> void:
	# Reading the file and loading the resource are two different questions. The importer's
	# own default for WAV is QOA, which is LOSSY - so this is the assertion standing between a
	# gate that checks lossless samples and a game that plays something else.
	var checked := 0
	for dir in _sfx_dirs():
		for path in ContentScan.files(dir, ["wav"]):
			var committed := SoundFile.read_wav(path)
			assert_object(committed).override_failure_message(
				"%s did not read as a WAV at all" % path).is_not_null()
			var imported := load(path) as AudioStreamWAV
			assert_object(imported).override_failure_message(
				"%s did not load as an AudioStreamWAV" % path).is_not_null()
			assert_int(imported.format).override_failure_message(
				"%s imports as format %d rather than 16-bit PCM - check compress/mode"
				% [path, imported.format]).is_equal(AudioStreamWAV.FORMAT_16_BITS)
			assert_int(imported.mix_rate).is_equal(committed.mix_rate)
			assert_bool(imported.stereo).is_equal(committed.stereo)
			assert_str(Hashing.sha256_bytes(imported.data)).override_failure_message(
				"%s: the imported stream is not the committed samples" % path).is_equal(
				Hashing.sha256_bytes(committed.data))
			checked += 1
	assert_int(checked).override_failure_message(
		"no cue was actually compared, so this proved nothing").is_greater(0)
