class_name TerrainEdges
extends RefCounted
## The edge between two materials, composed from QUARTERS of an artist's transition ring.
##
## Every reference game draws the boundary between grass and water as its own tile, and LPC
## ships the pieces for it: a 3x3 ring of edges and outer corners, plus four inner-corner
## notches. Thirteen shapes. That is not enough for this demo, and the reason is geometry
## rather than taste - the village pond is ONE tile tall and half the paths are ONE tile wide,
## so their cells need a north edge AND a south edge at once, which no single piece draws.
##
## So a cell's four QUARTERS are chosen independently and composed at generation time, which
## is RPG Maker's autotile scheme (secondhand - named from its format rather than from its
## source) and yields the full 47-shape "blob" set Tiled's own terrain documentation names.
## Thirteen pieces in, forty-seven shapes out, and the map format never learns about any of it.
##
## Everything here is PURE and integer. It runs inside the generator, whose output is compared
## byte for byte against committed PNGs on two operating systems, so there is no float
## arithmetic and no call into libm anywhere below - the same rule the rest of spritegen obeys.
##
## The vocabulary, once, because both halves of this file depend on reading it the same way:
## a neighbour is OPEN when it is the other material - the thing this tile has an edge
## against. A closed neighbour is more of the same material, or the edge of the map, or
## anything else at all. So `n` is the piece drawn when the material STOPS to the north.


# Clockwise from north, so a bit's neighbour is OFFSETS[its position] and the two orderings
# cannot drift apart.
const N := 1
const NE := 2
const E := 4
const SE := 8
const S := 16
const SW := 32
const W := 64
const NW := 128

## The eight neighbours, in bit order. A caller reads its map in this order once and hands the
## result to everything below.
const OFFSETS: Array[Vector2i] = [
	Vector2i(0, -1), Vector2i(1, -1), Vector2i(1, 0), Vector2i(1, 1),
	Vector2i(0, 1), Vector2i(-1, 1), Vector2i(-1, 0), Vector2i(-1, -1),
]

## The twelve pieces a bank must name: four edges, four outer corners, four inner notches.
## Checked as a set by TileBank.problems(), so a typo is refused by name rather than drawn as
## a hole - a missing piece is invisible while authoring, because each piece looks right alone.
const RING_KEYS: Array[String] = [
	"n", "e", "s", "w",
	"ne", "nw", "se", "sw",
	"ne_in", "nw_in", "se_in", "sw_in",
]

## The thirteenth, optional: what a quarter with no edge in it is filled from. Defaults to the
## tile's own plain cell, so an interior cell comes out identical to the flat tile that shipped
## before any of this existed - which is what lets a map with no shorelines in it be untouched.
const CENTRE_KEY := "c"

## The four orthogonals and the four diagonals, for counting. Typed, because an untyped array
## literal in a `for` makes its loop variable a Variant and this project warns on that.
const SIDES: Array[int] = [N, E, S, W]
const CORNERS: Array[int] = [NE, SE, SW, NW]

## The two orthogonals flanking each diagonal, in CORNERS order, and every side at once.
##
## Added rather than or-ed: the bits are disjoint so the value is the same, and `|` is the
## delimiter tools/mutants.tsv uses - a rule anchored on a line containing one cannot be aimed
## at, which would leave the normalisation below with no mutant to prove it.
const FLANKS: Array[int] = [N + E, E + S, S + W, W + N]
const SIDES_MASK := N + E + S + W

## Top-left, top-right, bottom-left, bottom-right. A quarter is taken from the SAME quarter of
## whichever piece it names: the top-left of the north edge is a north edge's top-left.
const QUARTERS: Array[String] = ["nw", "ne", "sw", "se"]

## Per quarter: its two orthogonal neighbours with the piece each one alone calls for, its
## diagonal, the outer corner both together call for, and the notch the diagonal alone calls
## for. A table rather than twenty branches, because the five cases are the same five for every
## quarter and a hand-written copy of them is four chances to transpose a letter.
const QUARTER_RULES := {
	"nw": {"v": N, "v_key": "n", "h": W, "h_key": "w", "d": NW, "corner": "nw", "notch": "nw_in"},
	"ne": {"v": N, "v_key": "n", "h": E, "h_key": "e", "d": NE, "corner": "ne", "notch": "ne_in"},
	"sw": {"v": S, "v_key": "s", "h": W, "h_key": "w", "d": SW, "corner": "sw", "notch": "sw_in"},
	"se": {"v": S, "v_key": "s", "h": E, "h_key": "e", "d": SE, "corner": "se", "notch": "se_in"},
}

## The 47 shapes, ascending, written out rather than derived.
##
## A literal because this is the SPEC: a table generated by the same rule the code applies is
## satisfied by construction, and a mutant that edits the rule would edit the expectation with
## it. `test_terrain_edges.gd` proves separately that every one of the 256 raw masks normalises
## into this list and that every entry is its own fixpoint, so the list and the rule check each
## other rather than one deriving the other.
const MASKS: Array[int] = [
	0, 1, 2, 4, 5, 8, 9, 10,
	16, 17, 18, 20, 21, 32, 33, 34,
	36, 37, 40, 41, 42, 64, 65, 66,
	68, 69, 72, 73, 74, 80, 81, 82,
	84, 85, 128, 130, 132, 136, 138, 144,
	146, 148, 160, 162, 164, 168, 170,
]


## Every key a ring may carry: the twelve pieces plus the optional centre. One list, so the
## bank's refusal and the generator's read cannot come to disagree about what a ring holds.
static func all_keys() -> Array[String]:
	var out: Array[String] = RING_KEYS.duplicate()
	out.append(CENTRE_KEY)
	return out


## The mask with every diagonal that cannot be seen dropped.
##
## A diagonal only ever chooses a NOTCH, and a notch is only reachable when neither neighbour
## beside it is open - if either is, that quarter is already an edge or an outer corner and the
## diagonal has nothing left to say. Dropping it is what collapses 256 raw readings into 47
## drawn ones, so two cells that must look identical ask for the same atlas cell.
static func normalise(mask: int) -> int:
	var out := mask & SIDES_MASK
	for i in CORNERS.size():
		if (mask & CORNERS[i]) != 0 and (mask & FLANKS[i]) == 0:
			out += CORNERS[i]
	return out


## Where this shape sits in the block of 47 a bank's edge entry owns. Never negative: every
## normalised mask is in MASKS, which is the property the coverage test pins.
static func index_of(mask: int) -> int:
	return MASKS.find(normalise(mask))


## Which neighbours are the other material, as a raw mask. `around` is the eight neighbour tile
## ids in OFFSETS order; a neighbour off the edge of the map arrives as "" and counts as closed,
## so a pond touching the map border does not grow a shoreline into the wall.
static func mask_of(around: PackedStringArray, over: Array[String]) -> int:
	var mask := 0
	for i in mini(around.size(), OFFSETS.size()):
		if over.has(around[i]):
			mask |= 1 << i
	return mask


## Which piece fills one quarter of a cell. The five cases, in the order they exclude each
## other: both sides open is a corner, one side open is that edge, neither side open with the
## diagonal open is a notch, and everything else is interior fill.
static func quarter_source(mask: int, quarter: String) -> String:
	var rule: Dictionary = QUARTER_RULES.get(quarter, {})
	if rule.is_empty():
		return CENTRE_KEY
	var vertical := (mask & int(rule["v"])) != 0
	var horizontal := (mask & int(rule["h"])) != 0
	if vertical and horizontal:
		return str(rule["corner"])
	if vertical:
		return str(rule["v_key"])
	if horizontal:
		return str(rule["h_key"])
	if (mask & int(rule["d"])) != 0:
		return str(rule["notch"])
	return CENTRE_KEY


## One composed cell: the ring's quarters laid over the material on the other side of the edge.
##
## `pieces` holds every RING_KEYS entry plus CENTRE_KEY, each a whole `size` tile; `base` is the
## plain tile of whatever this edge is drawn against, and it must be opaque - which the ground
## hole rule already guarantees for anything a map can name. The pieces are transparent OUTSIDE
## the material, which is the whole reason this composes rather than replaces: what shows
## through a piece's clear half is the neighbour's own ground, so a shoreline is grass meeting
## water rather than water meeting a guess about grass.
static func compose(mask: int, pieces: Dictionary, base: Image, size: int) -> Image:
	var out := base.get_region(Rect2i(0, 0, size, size))
	if out.get_format() != Image.FORMAT_RGBA8:
		out.convert(Image.FORMAT_RGBA8)
	var half := size / 2
	for quarter in QUARTERS:
		var piece: Image = pieces.get(quarter_source(mask, quarter)) as Image
		if piece == null:
			continue
		var at := _quarter_origin(quarter, half)
		for y in half:
			for x in half:
				var over := piece.get_pixel(at.x + x, at.y + y)
				if over.a8 == 0:
					continue
				out.set_pixel(at.x + x, at.y + y,
					_over(over, out.get_pixel(at.x + x, at.y + y)))
	return out


## Source-over, in whole bytes. Floats would put this render path one libm call away from
## differing between this Mac and the Ubuntu runner, and the drift gate compares the committed
## PNG byte for byte - so every channel is an integer from end to end. The base is opaque, so
## the result is too and the usual premultiplied division never arises.
static func _over(src: Color, dst: Color) -> Color:
	var a := src.a8
	var rest := 255 - a
	return Color8(
		(src.r8 * a + dst.r8 * rest + 127) / 255,
		(src.g8 * a + dst.g8 * rest + 127) / 255,
		(src.b8 * a + dst.b8 * rest + 127) / 255,
		255)


static func _quarter_origin(quarter: String, half: int) -> Vector2i:
	match quarter:
		"ne":
			return Vector2i(half, 0)
		"sw":
			return Vector2i(0, half)
		"se":
			return Vector2i(half, half)
		_:
			return Vector2i(0, 0)


## Which atlas column a cell draws, given every edge block its tile owns.
##
## The ONE lookup the world performs, so the runtime cost of all of this is a dictionary get
## and some bit arithmetic. A tile with no edges at all answers with the flat column it always
## did, which is what leaves every gb16 map and every interior identical to what shipped.
static func cell_index(edges: Array, around: PackedStringArray, plain_index: int) -> int:
	if edges.is_empty():
		return plain_index
	var chosen := pick_group(edges, around)
	var entry: Dictionary = edges[chosen]
	var over := JsonFile.to_string_array(entry.get("over", []))
	return int(entry.get("first", plain_index)) + index_of(mask_of(around, over))


## Which of a tile's edge blocks this cell is drawn against, when it could be drawn against
## more than one.
##
## Water borders grass in the village and dirt in the cave, and nothing stops a map from
## putting both beside one pool. Orthogonals decide it because they are what a player sees as
## the bank; diagonals break a tie; the earliest group breaks what is left, so the answer is
## the bank file's own order rather than whichever key a Dictionary happened to hand back.
static func pick_group(edges: Array, around: PackedStringArray) -> int:
	var best := 0
	var best_sides := -1
	var best_corners := -1
	for i in edges.size():
		var entry: Dictionary = edges[i]
		var mask := mask_of(around, JsonFile.to_string_array(entry.get("over", [])))
		var sides := 0
		var corners := 0
		for bit in SIDES:
			if (mask & bit) != 0:
				sides += 1
		for bit in CORNERS:
			if (mask & bit) != 0:
				corners += 1
		if sides > best_sides or (sides == best_sides and corners > best_corners):
			best = i
			best_sides = sides
			best_corners = corners
	return best
